git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
quitOnTopLevelReturn: true
keybinding:
  universal:
    return: <c-q>
    return-alt1: q
    quit: <c-c>
    rangeSelectDown: J
    rangeSelectUp: K
    nextBlock-alt2: <c-j>
    prevBlock-alt2: <c-k>
  commits:
    moveDownCommit: <s-up>
    moveUpCommit: <s-down>

gui:
  scrollPastBottom: false
  scrollHeight: 15
  # catppuccin theme
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'

  authorColors:
    '*': '#b4befe'
