#!/bin/bash
export PATH=~/.local/bin:~/.bin:$PATH
setxkbmap -option ''
setxkbmap -layout 'us, us'
setxkbmap -variant 'dvp,'
setxkbmap -option grp:alt_shift_toggle,grp:switch,grp_led:scroll,terminate:ctrl_alt_bksp
setxkbmap -option caps:escape
setxkbmap -option compose:ralt
xinput -disable "$(xinput -list | grep TrackPoint | sed 's/.*id=\([0-9]\+\).*/\1/')"

[ "$XDG_CURRENT_DESKTOP" = "KDE" ] || [ "$XDG_CURRENT_DESKTOP" = "GNOME" ] || export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_QPA_PLATFORMTHEME="qt5ct"

eval $(ssh-agent -s)
