[Personal]
# source        = imaps+xoauth2://me%40jeltef.nl@imap.gmail.com
# source-cred-cmd = oama access me@jeltef.nl
source        = notmuch://~/mail/
maildir-store = ~/mail/
outgoing      = smtps+xoauth2://me%40jeltef.nl@smtp.gmail.com
outgoing-cred-cmd = oama access me@jeltef.nl
default       = Postgres
from          = Jelte Fennema-Nio <postgres@jeltef.nl>
check-mail-cmd = mail-sync.sh
copy-to = Postgres,Interesting
